### ISSUE TITLE
Equivariant sdpvar objects

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#104]
Now that equivariants are implemented in the core code, we could generalize the idea of CommutantVars to also parameterize rectangular matrices invariant under left and right action by different representations.

**Comment by denisrosset** [comment]
Yes, I think this is very relevant, see also #103 .

**Comment by jdbancal** [comment]
This seems feasible now, and I love the idea :-)
Was thinking we could call the corresponding class EquiVar for short, or should we stick with full names, like EquivariantVariable?

**Comment by denisrosset** [comment]
I'm for consistent abbreviations, like we would do in a paper. The list of abbreviations used in RepLAB is here:
https://github.com/replab/replab/blob/master/docs/docs/abbreviations.md

So that would be `EquivariantVar` :)

**Comment by denisrosset** [comment]
Right now, I'm documenting and cleaning up the support of complex/quaternion division algebras in the `decompositiondispatch` branch, so we can bring the YALMIP stuff closer to what in RepLAB -- pretty exciting!

**Comment by jdbancal** [comment]
Oh, too bad :-/

Glad the documentation is progressing for division algebras though!

**Comment by denisrosset** [comment]
If you believe it's something that will appear repetitively in user code, we can have an alias for it. Like the `replab.S` function.

**Comment by jdbancal** [comment]
I think we need some time to see how things are appropriate or not for daily use. So maybe let's see how things go with usage, and if we have a clear reason to change things we'll still be able to do that: I think we should still be tolerant and allow for some API changes after a first release, because we don't have experience with the library yet.

**Comment by denisrosset** [comment]
That's already in with `.equivar`!
