### ISSUE TITLE
Include name of the function in documentation 

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#116]
Most of the documentation starts directly with a description of the function, without mentioning what is the name of the function being documented, as in the following example:
```
function output = increment(x)
% This function adds one to the provided number
%
% Arg:
%     x:double
%
% Returns:
%     output:double

    output = x+1;
end
```
The rendering of this documentation then produces the following output in matlab/octave:
```
This function adds one to the provided number

Arg:
    x:double

Returns:
    output:double
```
In other words, the help doesn't say what function it is documenting. It would be helpful to mention this name.

When a function has several arguments and/or outputs, it is also very useful to see the possible usages explicitly spelled out. This already constitutes a very good documentation by itself.

**Comment by jdbancal** [comment]
I see two simple ways to achieve this:

- Use the first line of the documentation for that. This is quite standard in documentation to start with a statement of the function together with its arguments/outputs. Here is an example:

```
function output = increment(x)
% output = increment(x)
%
% This function adds one to the provided number.
%
% Arg:
%     x:double
%
% Returns:
%     output:double

    output = x+1;
end
```

It renders as follows:
```
output = increment(x)

This function adds one to the provided number.

Arg:
    x:double

Returns:
    output:double
```

If any argument is optional, it can be signified and quickly identified with brackets:
```
output = increment(x, [delta])

This function adds one (or delta) to the provided number.

Arg:
    x:double
    delta:double (optional, default value is 1)

Returns:
    output:double
```

- Include a usage section in the documentation of the function. Here is what this would look like for the above function:
```
This function increments the provided number.

Usage:
    output = increment(x) : Adds 1 to x
    output = increment(x, delta): Adds delta to x

Arg:
    x:double
    delta:double (optional, default value is 1)

Returns:
    output:double
```

**Comment by jdbancal** [comment]
The CommutantVar class currently uses the first option, but it could be changed if necessary.

@denisrosset do you have any preference?

**Comment by denisrosset** [comment]
Regarding the usage stuff: I tend to avoid "dynamic dispatch" of stuff depending on the number and names of the arguments. RepLAB uses optional arguments at some places, but in general functions/methods do not change their behavior dramatically depending on how they are called.
(I have been burned by some GAP packages that use the same kind of convention, so I tend to be more "static-typed" language-like in my use of this feature).

So I'm not for a "Usage" section, but I'd be up for a "Example" section that provides a sample use -- that can be tested then as a docstring.

Regarding the duplication of the function name and argument: I know this is kind of the Matlab standard to put the function/method name on the first line, also TO PUT THAT NAME IN ALL CAPS. I'm not a big fan of that, neither of just duplicating the function declaration, but my opinion goes against the customs of the ecosystem (CVX and YALMIP both do as you mention).

That said, the documentation style of Matlab toolboxes is wildly inconsistent, so we may have a bit of wiggle room there.

Let's see if it plays well with the Sphinx generation tool. If it works, we can have this duplication. Otherwise, let's see how we can mitigate the incompatibility.

**Comment by denisrosset** [comment]
(Note: I like Sphinx very much for the ability of documenting several classes together on the same documentation page, and being able to tell the user how they relate)

**Comment by jdbancal** [comment]
Thanks for your feedback!

Just to clarify, the question here is not really about whether we should use dynamic dispatch or not; I think we already agreed to try to avoid that, and I'm not sure we use something like that at the moment. The question is rather about documentation formatting. As you say, there are still a few rare functions with optional argument, so I included this case to make sure that a documentation formatting specification would also describe how these arguments should be documented.

Also, the question is not whether we should use a "Usage" section or a "Example" section, but whether we should use a "Usage" section or start the documentation with the name of the function that the documentation describes. An "Example" section is certainly useful, but accomplishes a different purpose: primarily give one (or more) example of how the function can be called. This typically appears at the end of the documentation to illustrate a possible usage, not on the top to introduce the function and show its generic usage in a quick and concise way. Also, it might not be necessary to give examples for every internal and technical functions (that no user is supposed to use directly), but all bits of documentations should still be associated to a name.

I don't see a reason to put names IN ALL CAPS.

Do I read your response correctly in that you'ld suggest to go for 'duplication', and see how it plays with Sphinx?

**Comment by denisrosset** [comment]
Thanks for the clarifications. The ALL CAPS thing is what a few toolboxes still do. Matlab sometimes still puts names of functions in all caps (I don't remember where). Let's not do that indeed.

Regarding the documentation of optional parameters: in the current documentation style, I document the default values as part of the arguments documentation (which include much more than the type, compared to examples above).

For example
```matlab
        function rep = trivialRep(self, field, dimension)
        % Returns the trivial representation of this group on a finite dimensional vector space
        %
        % For convenience, either the representation can act on a real or complex vector space,
        % and multiple copies of the 1-dimensional trivial representation can be included, when
        % dimension > 1.
        % 
        % Args:
        %   field ({'R', 'C'}): Whether the representation is real (R) or complex (C)
        %   dimension (integer, optional): Representation dimension
        %                                  Default value 1
        %
        % Returns:
        %   replab.Rep: An instance of the trivial representation
```

**Comment by denisrosset** [comment]
I've looked around in Matlab toolboxes, the ones that use OO conventions, and I quite like the style of the unit test framework. For example

```matlab
        function suite = fromMethod(testClass, testMethod, varargin)
            % fromMethod - Create a suite from a single test method
            %
            %   SUITE = matlab.unittest.TestSuite.fromMethod(TESTCLASS, TESTMETHOD)
            %   creates a TestSuite from the test class described by TESTCLASS and the
            %   test method described by TESTMETHOD and returns it in SUITE. TESTCLASS
            %   is a meta.class instance which describes the desired test class. The
```

What do you think? and we keep the other documentation conventions, but just modify the first lines.

If we agree to a change, I'm not going to change every method today, but I'd consider harmonizing stuff when we actually have Sphinx running -- there will be other inconsistencies to correct, and that'd be the right time.

What do you think?

**Comment by jdbancal** [comment]
Ok no caps :)

I think it's ok to specify the optionality of an argument, when describing it specifically. We could keep that (if line widths are still manageable) and at the same time have brackets for these parameters in the first line: I find these brackets particularly useful to identify directly the easiest way to call a function, without having to read through the whole documentation.

What do you like exactly about the last example, it seems to include to descriptions: a 1-line description, then a longer. Would you like to have that as well? (not sure if it always makes sense, e.g. when a function appears to have just a very simple description, having both would mostly duplicate the explanation) Alternatively, having only one description would look like so:
```matlab
        function suite = fromMethod(testClass, testMethod, varargin)
            % suite = matlab.unittest.TestSuite.fromMethod(testclass, testmethod)
            %
            % Creates a TestSuite from the test class described by testclass and the
            % test method described by testmethod and returns it in suite. testclass
            % is a meta.class instance which describes the desired test class. The
```

**Comment by denisrosset** [comment]
Sphinx advocates having a 1-line summary that does not use any inline math or argument names. 

Then, if necessary, a longer description that can refer using backticks to other method names, argument names, etc...

I found that it worked pretty well when documenting RepLAB (which includes now around 3'000 lines of comments!)

(I like having 1-line summaries to skim, and for future use - too bad the `help` function does not extract them. It would be cool, for example, to list all methods of a class with the accompanying 1-line summaries.)

**Comment by jdbancal** [comment]
If the 1-line summary starts with the name of the function, it's not a problem to have it. Ok, then the long description is only provided if needed.

And do you want to tab also the whole documentation except the first line, as in the unit test framework example?

**Comment by denisrosset** [comment]
I wouldn't tab. Whitespace is mildly significant for Sphinx, and I don't know the impact.

**Comment by jdbancal** [comment]
All right! Then I think we have a guideline :)

Here are two examples for reference:
```matlab
function suite = fromMethod(testClass, testMethod, varargin)
    % fromMethod - Create a suite from a single test method
    %
    % suite = matlab.unittest.TestSuite.fromMethod(testclass, testmethod)
    % creates a TestSuite from the test class described by testclass and the
    % test method described by testmethod and returns it in suite. testclass
    % is a meta.class instance which describes the desired test class. The
    % ...
```
```matlab
function replab_addpaths(verbose)
    % replab_addpaths - Sets up path for RepLAB
    %
    % replab_addpaths([verbose])
    % Sets up the search path in order to enable all functionalities of the
    % RepLAB library.
    % ...
```

**Comment by denisrosset** [comment]
I guess this issue is resolved, right? Or is there any insight from the discussion that we can move to the documentation?

**Comment by jdbancal** [comment]
My impression is that the documentation guidelines were updated accordingly, but not the actual documentation: function documentations currently don't include the new format. Should we not update the function "documentation comments" before closing this issue?

**Comment by denisrosset** [comment]
That's right!

**Comment by denisrosset** [comment]
Name is automatically added by the `help` function in the `topic/infra2` branch.
