### ISSUE TITLE
Compatibility of replab objects with save/load

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#122]
- Is it supported out of the box?
    - Use of function handles?
    - Compatibility across octave/matlab?
    - Compatibility across windows/linux/mac?
- Do we want to support it for some specific functions?

**Comment by denisrosset** [comment]
For now, we don't have compatibility guarantees. Save/load under Octave doesn't seem to work.

Add an `import`/`export` method pair for `Irreducible` so that information can be preserved across runs (but do not try to serialize groups, representations etc.)

**Comment by denisrosset** [comment]
Change of mind: for 1.0 document that load/save should work under Matlab, but is experimental.

**Comment by denisrosset** [comment]
Done
