### ISSUE TITLE
Add Gitter room to the project?

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#140]
I just created a replab/replab Gitter room; should we add it to the documentation?

https://gitter.im/replab/replab

**Comment by jdbancal** [comment]
Sure!

By the way, how should we understand gitter chats, compared to the possibility of discussing items in github issues for instance: what is its intended role exactly? e.g. which discussion should go where?

**Comment by denisrosset** [comment]
I'm thinking of info that are kind of real-time, and don't need to be archived; i.e. "I'm going to merge this, is anybody working on piece of code X"

Also, could have questions from users

See https://gitter.im/typelevel/cats-dev for an example. We *don't* need absolutely to have a Gitter channel.

**Comment by jdbancal** [comment]
I see, good to know what should be communicated on which platform :-)

**Comment by denisrosset** [comment]
Done already. But isn't used much, so I opened a https://github.com/replab/replab/discussions thing
