### ISSUE TITLE
Have RepLAB select appropriate terminal width/height defaults

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#141]
We could replace the defaults in `+replab/Parameters.m` by appropriate values obtained from:

`matlab.desktop...`
https://www.mathworks.com/help/matlab/ref/commandwindow.html

(`terminal_size`)
https://octave.org/doc/v4.2.1/Terminal-Output.html

**Comment by jdbancal** [comment]
Yes, very good idea!

**Comment by denisrosset** [comment]
Done.
