### ISSUE TITLE
update doc

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#157]
- [x] On main page, shortcuts are to the 5 main topics
- [x] On main page: add link to https://www.divio.com/blog/documentation/
- [ ] Clean articles
- [ ] Add a few first how-to's
- [ ] Clean-up the SDP how-to

**Comment by denisrosset** [comment]
Let's wait on #178 before doing clean up work

**Comment by denisrosset** [comment]
TODO: split this issue into several smaller issues
