### ISSUE TITLE
Group enumeration displaying fails for large groups

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#16]
The following code:
```
replab.Permutations(100).elements
```
yields a `horzcat error: Dimensions of arrays being concatenated are not consistent.`. The reason is that the `num2str` method of VPI inserts newline characters in the middle of long numbers. The resulting string is then not a single-line string any more, and cannot be concatenated with other single-line strings.

**Comment by jdbancal** [comment]
Note that the command `replab.Permutations(100).order` also produces a multi-line output. This is not a bug per se, but I'ld suggest that it would be nice to avoid this behavior as well.

One nice way to do so would be to provide a string method for VPI which always produces one-liners. The fix of this bug provided in #15 could then be removed.

**Comment by denisrosset** [comment]
Corrected by the new pretty printing framework.
