### ISSUE TITLE
The documentation infrastructure should support different `root` paths

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#164]
In our use, we have scripts `replab_init` and `replab_easyinstall` outside the `src` directory; and the `help` function should be able to work with them.

**Comment by jdbancal** [comment]
Hmm, if I call `help replab_init` I receive help for this function, as formatted by matlab. Would you expect another behavior?

**Comment by denisrosset** [comment]
You're right.

That said, I'm making a copy of those files so that Sphinx can index them.

**Comment by denisrosset** [comment]
Closing this as this is addressed by #194
