### ISSUE TITLE
Link to github page from website

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#200]
It would be convenient to have a direct link from the main page to https://github.com/replab/replab

**Comment by denisrosset** [comment]
I added a small link; some kind of logo in the sidebar would be good, leaving this open

**Comment by jdbancal** [comment]
It seems that since #206 there is now indeed a logo in the sidebar, which is very nice! As well as links to the latest download, travis, etc.

**Comment by denisrosset** [comment]
Can we close this issue then?

**Comment by jdbancal** [comment]
I think so, closing
