### ISSUE TITLE
Using `:` in return types confuses Sphinx

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#205]
If we write `  cell{:,1} of charstring: The returned list of strings` in a `Returns:` block, Sphinx understands that the type is `cell{`, as it parses the line until the first colon `:`.

Suggestion: switch to the `  cell{*,1} of charstring` syntax

@jdbancal Suggestions?

**Comment by jdbancal** [comment]
Haha, didn't see this coming ;-D

With a star we definitely start mixing matlab notation with generic search convention, resulting in a mixture of our own. I guess Sphinx doesn't have support for structured types anyway... Does `cell{*,1} of something` actually work?

**Comment by denisrosset** [comment]
I've started to use that, see https://replab.github.io/replab/api/infrastructure.html#+replab.+infra.CodeBase.allClasses

It seems to work. Indeed, we are mixing our convention with the new one pushed by Matlab (see https://www.mathworks.com/help/matlab/matlab_prog/function-argument-validation-1.html )

I don't see a way out without either fully preprocessing the documentation comments (I'd like to avoid that), or hacking Sphinx / Sphinx Matlab domain (I'd like to avoid that too)

Are we happy standardizing on `cell{*,1}`?

**Comment by denisrosset** [comment]
BTW, the MATLAB official syntax is `cell(*,1)`, not `cell{1,*}`. I suggest we match theirs.

**Comment by jdbancal** [comment]
Is `cell(1,*)` also an official syntax or is it that only the first dimension can accept a star officially?

It's true it is not very logical to say `cell` and also have the curly brackets `{}`. But actually, if we don't follow matlab's format, maybe a more compact and systematic format would be to use, not
```
charstring(*,1)
```
for an array of charstrings, and
```
charstring{*,1}
```
for a cell array of charstrings, instead of
```
cell(*,1) of charstring
```


(This issue is a bit of a follow-up to #153.)

**Comment by denisrosset** [comment]
I'd still like to keep `cell(1,*) of`, because it's more regular, and is likely to interact better with the backtick syntax of Sphinx (otherwise, we'd have something like 
```
`+replab.Rep`{1,*}
```

and Sphinx likes a lot having its special characters well separated.

On that note, the notation `cell(1,*)` conflicts with the use of `*` for the emphasis syntax. The solution for that is to escape the `*` as `\*` in the plain text.

**Comment by jdbancal** [comment]
All right! So then it would be
```
double(1,\*)
```
for an `1xn` array of double, and 
```
cell(1,\*) of double
```
for a `1xn` cell array of double, correct?

**Comment by denisrosset** [comment]
Yes, absolutely! Closing this for now, as it is handled #236
