### ISSUE TITLE
Implement a license compatible Levenberg-Marquart curve fitting algorithm

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#214]
Right now, we use either an Octave package (GPL3), or a nonfree Matlab toolbox.

Still, the algorithm is a few lines of code and should not be difficult to implement.

**Comment by jdbancal** [comment]
Currently, we use this algorithm to fit a function with 3 parameters. This constitutes is a nonlinear optimization, but probably not a too crazy one. What about using `fminunc` instead here? This should be available on both matlab and octave, right?

**Comment by denisrosset** [comment]
A least squares fit has special structure, and can be solved with a simpler algorithm than `fminunc`. For example, only the Jacobian of the nonlinear function needs to be known, the Hessian never enters the picture.

`fminunc` requires the optimization toolbox, so the problem would be the same. However, the Levenberg-Marquardt algorithm is simpler to reimplement than a general nonlinear fit algorithm.

**Comment by denisrosset** [comment]
Implemented in 1de0e3fc4feead76adeef4348ae9fd9baec3435e
