### ISSUE TITLE
Escape `*` in documentation comments

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#236]
Sphinx reserves `*` as a special character, so it needs to be escaped in uses such as `double(1,*)` as `double(1,\*)`.

This is a tad ugly in the code (on the other hand we already have `+` prefixes everywhere ...).

I propose to escape, with the plan below.

- [ ] grep code and escape all stars in documented types (and perhaps former uses of `:`)
- [ ] filter those characters in the REPL help formatting output
- [ ] verify that Sphinx doesn't emit warnings about those characters anymore

See #205

**Comment by jdbancal** [comment]
`\*` is probably not very likely to appear in the documentation, except in these cases, so that sound all right
