### ISSUE TITLE
SDPT3 compilation fail not detected by `replab_init`

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#241]
I'm running the tests on my laptop under Octave and Ubuntu 19.10, but I hadn't installed the `liboctave-dev` package and thus SDPT3 compilation failed.

The compilation step failed, but `replab_init` did not show any errors; when running the `install_sdpt3` script, the error is detected but no explanation of the error is displayed.

**Comment by jdbancal** [comment]
I think this was fixed in 1265ec429a7a791defe38fb89da8194351b48363
