### ISSUE TITLE
Create sdp matrix from index matrix without any symmetry

### ISSUE THREAD

**Issue by marieio** [replab/replab#248]
Hey,
I am trying to generate an sdp matrix with an array of indices. Each entry with the same index should have the same sdpvar. I don't have any symmetry, so I just left the {permutation} field blank. I get the following error message: 

Index exceeds the number of array elements (0).

Error in replab.CommutantVar (line 193)
            n = size(generators{1}, 2);

Error in replab.CommutantVar.fromIndexMatrix (line 892)
            R = replab.CommutantVar(generators, sdpMatrix, 1, matrixType, field);

Error in newG (line 24)
cstrSdpMatrix = replab.CommutantVar.fromIndexMatrix(indexMatrix, {}, 'hermitian', 'complex')

Could you help please?
Thank you
Marie

**Comment by jdbancal** [comment]
I could reproduce the error with the command
```
replab.CommutantVar.fromIndexMatrix(ones(3,3),{},'full','real')
```
