### ISSUE TITLE
Dual licensing under Mozilla Public License and General Public License

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#29]
I'm making RepLAB compatible with the Quaternion toolbox, see https://sourceforge.net/projects/qtfm/

As QTFM is licensed under the GPL, I'd like to make RepLAB dual licensed.

@jdbancal and @bogdan98 : are you OK to relicense your contributions under the GPL v3 as well?

**Comment by jdbancal** [comment]
I don't see a problem with adding the GPL license, but I also don't see the necessity for dual licensing: as I understand, dual licensing is usually used to allow a GPL product to be integrated into a paid bundle (c.f. https://resources.whitesourcesoftware.com/blog-whitesource/dual-licensing-for-open-source-components-yeah-or-meh), but this is not our situation...

Note also that MPL2 is compatible with GPL in the sense defined in https://www.gnu.org/licenses/license-list.html. What relation do you have in mind for RepLAB and QTFM? What is the problem we are trying to solve here exactly? And how would dual licensing solve it?

**Comment by denisrosset** [comment]
I'm going to use QTFM to decompose quaternion-type real representations, as it provides full support for eigenvalue decomposition, etc...

Thus, it's RepLAB that embeds QTFM, not RepLAB being embedded in a GPL project.

In the end:

- if somebody uses quaternion support, RepLAB will be _de facto_ under GPL, as it gets taken by the viral nature of QTFM's GPL,
- when somebody doesn't use quaternion support, RepLAB is still under the MPL.

I want to remove the need to embed QTFM in the future. There are other, less complete, quaternion libraries for Matlab and there is no reason we can't code a 4x4 quaternion eigenvalue decomposition algorithm under MPL. But for now, I'm following the shortest route towards robust and simple code.

The issue is just to check that you're OK with that.

**Comment by jdbancal** [comment]
Thanks for the clarification! That's very helpful :-)

If we are to embed QTFM, it seems we should indeed provide a GPL license option. The only alternative I see would be to ask the user create the final product by letting him download both libraries independently, but I would really not be in favor of that. I guess the MPL license is still meaningful as it can be chosen if some sections which don't rely on QTFM are extracted from the code, as well as if the whole QTFM code is removed one day. So green lights for me.

**Comment by denisrosset** [comment]
That's exactly the point. I hope to remove the dependency on QTFM for the basic operations of RepLAB in the future (but we may want to keep compatibility with it).

**Comment by denisrosset** [comment]
QTFM has been removed, so the issue is closed.
