### ISSUE TITLE
Define equality semantics

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#31]
When comparing objects such as groups, do we use `isequal` or `eq`?
Do we consider two instances of isomorphic groups to be equal?
(For example, when calling `replab.Permutations(4)` twice)
Should we give the user the option of naming instances of groups?

**Comment by denisrosset** [comment]
Note that Octave does not like the use of the default operator `==` (or `eq`) for handles.

**Comment by jdbancal** [comment]
`eq` and `isequal` don't have the same purpose. Here is what the matlab documentation `help isequal` says:

```
When comparing handle objects, use EQ or the == operator to test
whether objects are the same handle. Use isequal to test if objects
have equal property values, even if those objects are different
handles.
```
If when comparing two groups we are interested to check whether they are the same element logical (mathematical) object, I'ld use `isequal`. If we want to return whether the two objects refer to the same element in the computer memory, I'ld use `eq`.

**Comment by denisrosset** [comment]
I removed the methods that required sane handling of equality. Will come back to this later.

**Comment by denisrosset** [comment]
With @jdbancal : we do not prescribe `isequal` or `==` semantics. For selected objects, we propose a specialized method for comparison, such as `isSameGroupAs`.

**Comment by denisrosset** [comment]
This evolved pretty well.
- Finite groups of the same type can be compared.
- Compact groups in general cannot.
- Representations cannot be compared (at which level would we compare them? same images? what about SubRep and injection/projection maps, etc.)
- Cyclotomic matrices can of course be compared
