### ISSUE TITLE
Support for cached properties

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#322]
Right now, RepLAB uses the pattern of

- a protected property `thing_`,
- a method `computeThing`
- an access method `thing` that checks if `thing_` is empty, computes the value and stores it if necessary, and returns the cached value

This introduces a lot of boilerplate.

The alternative is to introduce a `cache` struct in `replab.Obj` which contains the known computed properties; and a `cached` method that performs the logic above: check if the property is stored in `cache`, call `computeThing` if necessary and stores the computed value in the cache, returns the value.

It would obscure the logic a little bit for the people working on the code, but reduce the boilerplate by a lot. And then we'd be comfortable caching more things in `NiceFiniteGroup`: the conjugacy classes, the derived subgroup, the recognized form of the group, the center, logical things like `isCyclic`, `isSimple`, the exponent, ...

**Comment by jdbancal** [comment]
Sounds good to reduce code duplication and maintainance!

One thing though: having all variables of a class appearing in the `property` section is super useful for the programmers to just know in the glimpse of an eye what elements the class potentially holds inside. If a new property can be created programmatically by calling a function like `cache('nameOfNewProperty, ...)` it may become hard to keep a vision of what each class is holding exactly, and thus the role of each object may become harder to grasp. One way to mitigate this risk could be to take advantage of #324 and choose to:
 1. Request that each cached property must have a dedicated access method with same same in the class
 1. Put all these methods giving access to a cache property in a dedicated methods section appearing before the constructor (i.e. right after the actual `property` section)

**Comment by denisrosset** [comment]
Actually, the cached properties always had to be accessed through a method, because the corresponding `property_` has protected access.

Yes for the requirement number 1.

It'd be also possible for 2., except that for understanding, it's also great to have the `computeProperty` function close to the `property` one. I'm doing a clean up of `FiniteGroup` / `PermutationGroup` / `NiceFiniteGroup`, we will be able to discuss on a real case how it should look like.

Also yes #324 is becoming crucial, those classes are mighty!
