### ISSUE TITLE
Only compute group order if needed

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#348]
Since 3eebb17f1c9ffc0ca8e8144dc11c5302d904b083 it seems that the order of the symmetric group is systematically computed upon creation. This makes it essentially impractical to work with subgroups of S(n) when n is large (since the definition of such subgroup typically involves first the creation of S(n)).

If we really want to set the order upon creation of `replab.SymmetricGroup` objects, maybe we should only compute it for small n...

For reference, here is the basic timing of the `factorial` function :
```
>> tic;factorial(vpi(10));toc
Elapsed time is 0.032294 seconds.
>> tic;factorial(vpi(100));toc
Elapsed time is 0.036269 seconds.
>> tic;factorial(vpi(1000));toc
Elapsed time is 0.116162 seconds.
>> tic;factorial(vpi(10000));toc
Elapsed time is 7.641215 seconds.
>> tic;factorial(vpi(30000));toc
Elapsed time is 137.611941 seconds.
```

**Comment by denisrosset** [comment]
Indeed, good point! The trick is that knowing the order makes the computation of the stabilizer chain faster.

I guess the main problem is that ``vpi`` is very slow. The same computations using `java.math.BigInteger` takes a fraction of a second.

There is actually already a function that offloads multiplications to `java.math.BigInteger`. Let's use it.

**Comment by jdbancal** [comment]
Good idea! `java.math.BigInteger` is indeed much better than `factorial` on `vpi` objects:
```
>> tic; replab.util.multiplyIntegers(1:100); toc
Elapsed time is 0.046563 seconds.
>> tic; replab.util.multiplyIntegers(1:1000); toc
Elapsed time is 0.094218 seconds.
>> tic; replab.util.multiplyIntegers(1:10000); toc
Elapsed time is 0.600822 seconds.
>> tic; replab.util.multiplyIntegers(1:100000); toc
Elapsed time is 8.403112 seconds.
```
Essentially, we gain one order of magnitude like this :-)

However, I don't have the impression that this addresses the main issue: a group order still gets computed even when it is not necessary, hence reopening the issue.

Maybe it's useful to distinguish here between "knowing" the group order as in knowing a formula for it, and knowing its decimal representation. The first one is trivial for the symmetric group, just `factorial(n)` but the second one can be quite nontrivial. Actually, not only is it nontrivial to compute the digits of something like `order(S(1e6))`, it is also not clear whether this can be useful (this number is so huge, can obtain something by manipulating it?), hence maybe we should not try to compute it systematically for arbitrarily large values of `n`...

Just like we don't compute the bsgs chain for a group unless we need it (actually not even for S(n) at the moment, right?), it would help if the order of a group is only computed when needed, even for S(n). For instance, if it is useful to compute the bsgs chain, could we compute it at that point?
