### ISSUE TITLE
Dependencies are not bundled with the ZIP release

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#37]
Currently, we use submodules to "bundle" the following dependencies with RepLAB:
- YALMIP and SDPT3 (this is a problem)
- MoXUnit and MOCov (this is not crucial for users)

However, those are not present in the ZIP package that can be downloaded in a user-friendly way front the RepLAB repository main page.

This is a known problem:
https://github.com/dear-github/dear-github/issues/214

Should we bundle at least YALMIP and SDPT3 with RepLAB?

**Comment by jdbancal** [comment]
Yalmip and sdpt3 are also not needed to be provided in the release. I would not include them in a release, whether manually or automatically.

Yalmip is an autonomous project, and in the end, a user who will wish to use the part of our project which depends on yalmip will have to type some yalmip command by himself, and therefore learn about it to some extend. He should expect to find help about it on the yalmip website, not on ours. Therefore, I think it is best to ask the user to install yalmip independently of replab on his system. This is slightly more work to get started but:
- The user should then realize that yalmip is a distinct project and that he can learn about it independently
- If one version of yalmip is set up in the path, then this version will be used by the add_path script, so all should work seemlessly.

Concerning sdpt3, it is just included here as one possible sdp solver, but performing any full install of yalmip (i.e. with at least one sdp solver) would be equally good. No need for sdpt3 per se.

Maybe we could give a short howto for people downloading the zip release to follow. This would essentially say:
- download the zip
- install yalmip with a working sdp solver (we can refer to a page explaining thus on the yalmip doc)
- follow the examples given on page [...], starting with the add_path script

If a user prefers to get started fully-magically, without arranging several downloads, he should try the git methodology, it puts everything in place with the fewest keystrokes and it was kind of meant for that ;-)

**Comment by denisrosset** [comment]
I guess we can just direct people to unzip the Yalmip + SDPT3 releases in the `extern/` folder. Let's update the documentation.

**Comment by denisrosset** [comment]
I just edited the documentation in that respect, see 

https://github.com/replab/replab/pull/40

(in particular, I think there was a doc mistake, please verify)

**Comment by jdbancal** [comment]
Following our discussion, it would be good to have a `replab_addpackages` script for *Automagical download and installation of partner software*. Matlab has functions (`websave`, `unzip`) that can be used for that, but `websave` is not yet available in Octave...

**Comment by denisrosset** [comment]
See #107 , it's coming! and works with Octave

**Comment by denisrosset** [comment]
It's in the main repo but labelled as experimental.

@jdbancal What would be the criteria to close this issue? For me:

1. @jdbancal reviewing it, and us removing the "experimental" label.
2. Updating the installation documentation to advocate its use.
3. Deciding what we do when dependencies needs an upgrade. Do we have a versioning scheme for our "dependency pack"? Do we simply require users to erase the subfolders in `extern/` and run the script again?
4. Do we test this script as part of continuous integration, and how?

**Comment by jdbancal** [comment]
Ok, if I understand, we do this because of need by general users.

Was this tested on windows? (many people use this os...)

Regarding the points:

1. Let's make this part of the official project!
2. Yes, then we should probably remove the description of "manually downloading and unpacking" the external libraries. It might be good, though, to keep a description of what is included in the externals and why.
3. I'ld say we have two options:
    - Either we keep the current download location on a specific branch, then I'ld make it simple: the location always contains just the latest version of externals (i.e. if the user wants to fine tweak anything else, just use git)
    - Or we provide the zip file as an asset attached to each release `https://github.com/replab/replab/releases`. Then we can keep everything up to date, we just need to adjust the download location according to the current version. (In this case we 
4. This might be painful if we don't update the externals... (imagine pushing something which needs a new external, either it will fail because the external has not been updated, or it will succeed with the new external, but other branches which rely on a previous version of the external will start to fail...). Maybe we think about this at a later stage once we are confident that the infrastructure is stabilized?

**Comment by jdbancal** [comment]
Great work, by the way, significantly increases user friendliness :)

**Comment by denisrosset** [comment]
Quick comments:

1. Works on Windows using Matlab. TBD on Octave/Windows #123 
2. After discussion with @jdbancal, we store the ZIP artifact on an `externals` branch as we do now
3. There is no support of versioning in the script; it fetches always the latest ZIP file on the externals branch. However, Git will keep track of older versions if needed. We do not expect old versions of RepLAB to break with newer versions of the dependencies -- but if that happens, the old ZIP file is still in the history.
4. The script is not run as part of the continuous integration. Anyway, we do not expect big changes to it.

**Comment by denisrosset** [comment]
Now solved!
