### ISSUE TITLE
CommutantVar.fromIndexMatrix crashes on non-positive indices

### ISSUE THREAD

**Issue by alastair-abbott** [replab/replab#388]
The documentation for CommutantVar.fromIndexMatrix asks for an indexMatrix of arbitrary integer values. However, it seems in practice these must strictly positive integers.

I see two possible paths:
1) Correct the documentation to make it clear the indices must be positive; or
2) Make it work for arbitrary indices (it's sometimes useful to use negative indices as special flags, for example). This could easily be achieved by, e.g., simply adding a constant to make the indexMatrix positive if it's not already with negligible cost.

**Comment by jdbancal** [comment]
Thanks for reporting this issue Alastair!

Concerning the meaning of the word `integer` in the documentation, there are situations in which those integers are clearly expected to be positive (e.g. the number of elements to be permuted in `S(n)`), and others where the opposite should also be clear. In the specific case, however, I agree that the context does not make it clear whether the numbers can be negative or not.

Upon thinking a bit more about it, negative integers could also be quite useful to signify that a variable comes with an opposite sign. For instance, when dealing with an antisymmetric matrix (or the imaginary part of a hermitian matrix), this reduces the number of variable by two. Do you think it would be better to enable negative integers to encode a sign inversion like here? Or would it be more useful to enable it to be some simple additional variables?

As you say, the former can be accomplished easily (with only a very mild risk of overflow) by performing
```
indexMatrix = indexMatrix - min(min(indexMatrix)) + 1;
```

**Comment by alastair-abbott** [comment]
That's a good point actually.  Maybe it would be a nice feature to treat negative indices in this way, although I'll let you make the final call on that ;-)

**Comment by jdbancal** [comment]
Ok, then let's do that!
