### ISSUE TITLE
Displaying unsimplified fractions in `+replab.cyclotomic.fromDouble`

### ISSUE THREAD

**Issue by jvdv37** [replab/replab#402]
`replab.cyclotomic.fromString({'6/1000'})` returns 3/500
`replab.cyclotomic.fromDouble(6/1000)` returns 3458764513820541/576460752303423488
In general, `fromDouble` returns large multiples of fractions unless input is a simple double like 0.5

**Comment by denisrosset** [comment]
Yes! that's because fractions with a denominator that's not a power of two cannot be exactly represented using floating-point numbers!

**Comment by denisrosset** [comment]
Closing this because it's by design!
