### ISSUE TITLE
Why do we check if the *parent* directory of the RepLAB directory can be modified?

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#405]
@jdbancal There is a check in `replab_easyinstall`, forgot why we put it there

**Comment by jdbancal** [comment]
I think this is related to an old mechanism we had to test for the presence of another copy of RepLAB in the path. Now that this is achieved by scanning manually all matches of `replab_init` in the path, I guess we wouldn't need it anymore. Good catch!
