### ISSUE TITLE
Group of 6 elements generated as a subgroup of S(5)

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#415]
The following command
```
replab.S(5).subgroup({[2 3 1 4 5], [1 2 3 5 4]})
```
recognizes the group as
```
recognize: AtlasResult (Cyclic group C(6) of order 6)
```
although it contains only 5 elements

**Comment by jdbancal** [comment]
Same here:
```
group = S5.subgroup({[2 1 4 5 3]})
```

**Comment by denisrosset** [comment]
Both groups have 6 elements! it recognizes the group as an abstract structure, not as a permutation group cycling through 5 elements.

**Comment by jdbancal** [comment]
I agree that both group have 6, thanks!
How can RepLAB convince me that this group is indeed C6?-) Is it possible to extract the mapping and see what how the generator of C(6) acts on this group?

**Comment by denisrosset** [comment]
On the second one:
```
>> group.recognize
ans = 
AtlasResult (Cyclic group C(6) of order 6)
        atlasGroup: < x | x^6 = 1 >
standardGenerators: {[2, 1, 4, 5, 3]}
         userGroup: Permutation group acting on 5 elements of order 6
presentationString: '< x | x^6 = 1 >'
```
`standardGenerators` gives you the generators of the `atlasGroup`, i.e. the generators in the "canonical" presentation.
And indeed:
```
>> replab.Permutation.order([2 1 4 5 3])
ans =
     6 
```

**Comment by jdbancal** [comment]
Awesome! Thanks for the demo with recognize! :+1:
