### ISSUE TITLE
Operations on groups ignore recognization limits

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#452]
When defining a group of order larger than `replab.globals.fastChainOrder`, the group rightly does not go into the recognize procedure (this quickly becomes slow for large groups and is only needed for nice display). This behavior can be seen here:

```
> n=8; grp=replab.S(n)

grp = 

Symmetric group acting on 8 elements
  domainSize: 8
    identity: [1, 2, 3, 4, 5, 6, 7, 8]
        type: Symmetric group acting on 8 elements
generator(1): [2, 3, 4, 5, 6, 7, 8, 1]
generator(2): [2, 1, 3, 4, 5, 6, 7, 8]
```
The group `grp` is not recognized as S(8).

However, when the same group is created, but in different ways, it seems that the limit is not applied anymore:
```
>> grp.intersection(grp)

ans = 

Permutation group acting on 8 elements of order 40320
  domainSize: 8
    identity: [1, 2, 3, 4, 5, 6, 7, 8]
        type: Symmetric group acting on 8 elements
generator(1): [2, 1, 3, 4, 5, 6, 7, 8]
generator(2): [1, 3, 2, 4, 5, 6, 7, 8]
generator(3): [1, 2, 4, 3, 5, 6, 7, 8]
generator(4): [1, 2, 3, 5, 4, 6, 7, 8]
generator(5): [1, 2, 3, 4, 6, 5, 7, 8]
generator(6): [1, 2, 3, 4, 5, 7, 6, 8]
generator(7): [1, 2, 3, 4, 5, 6, 8, 7]
   recognize: AtlasResult (Symmetric group S(8) of degree 8)
>> replab.globals.fastChainOrder

ans =

       10000
```
Here, the limit on the group size for recognition is 10000, but a group of size 40320 was tested. When dealing with larger groups, this quickly blocks all computation.

**Comment by jdbancal** [comment]
Here is a simple example showing that the limit on the group order is sometimes ignored. The following command should create an instance of S(10) and print it, but it does not finish (takes forever)
```
replab.PermutationGroup.of([2     1     3     4     5     6     7     8     9    10], [2     3     4     5     6     7     8     9    10     1])
```

**Comment by denisrosset** [comment]
There were a few things that contributed to this, it's fixed now.
