### ISSUE TITLE
Crash in initHelp

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#479]
This happened on N.G.'s computer. Steps to reproduce:

1. Start with a fresh Matlab install, using the GUI interface
2. Run replab_init
3. Click on the "Set Path" toolbar button, save the path
4. Exit Matlab
5. Start Matlab again
6. Run `replab_init`, the script will crash with the error below.

I've been unable to reproduce the error on Linux.

![IMG_20210129_151613569](https://user-images.githubusercontent.com/93707/106286802-564c3600-6246-11eb-8267-3ee6568ae66a.jpg)

**Comment by jdbancal** [comment]
Quels sont les paths qui dirigent vers des versions jugées 'différentes' de matlab?

**Comment by jdbancal** [comment]
Est-ce que c'es juste une histoire de backslash vs forwardslash?

**Comment by denisrosset** [comment]
I don't have access to the computer where this happened any more; can you try it on your computer?

Otherwise, I'll ask N.G. to borrow his computer at some stage.

**Comment by denisrosset** [comment]
(Note : there aren't two different versions of RepLAB on the computer, actually `replab_init` comes from the one that was added to the path before, so no shenanigans there)

**Comment by jdbancal** [comment]
There is no backslash on linux, only forwardshash, so I suppose there is no chance this will happen on linux

**Comment by denisrosset** [comment]
> Est-ce que c'es juste une histoire de backslash vs forwardslash?

Yes indeed! this is what it looks like on the screenshot. Should be easy enough to fix.

**Comment by jdbancal** [comment]
Indeed

**Comment by jdbancal** [comment]
I merged what should fix this, but can't test it so leaving the issue open. @denisrosset can you close it after you had a chance of checking on NG's computer whether the fix is sufficient?

**Comment by jdbancal** [comment]
Confirmed solved on the original system so closing
