### ISSUE TITLE
Ordered vs unordered chain basis in permutation group

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#483]
`replab.PermutationGroup` admits two BSGS chains: `chain` and `lexChain`. `lexChain` must have a strictly increasing basis. When providing a `chain` as an argument to the constructor, it seems that it however forces its basis to be ordered as well (hence not really using the provided BSGS chain)

**Comment by denisrosset** [comment]
This is indeed a discrepancy. I'm removing the "basis forcing".
