### ISSUE TITLE
Add the FillOrbits from Minkwitz 1998 paper 

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#5]
The word factorization algorithm could be improved by implementing the procedure FillOrbits described in
http://www.sciencedirect.com/science/article/pii/S0747717198902024

**Comment by bogdan98** [comment]
Is anyone working on that issue at the moment? If not, I could try to resolve it (just tell me please where the code for the algorithm itself is).

**Comment by denisrosset** [comment]
The code is in https://github.com/replab/replab/blob/master/%2Breplab/%2Bbsgs/Chain.m , although the BSGS code in RepLAB is currently a mix of generic and specialized code.

It's not the part of RepLAB I'm the most proud of, as it mixes the construction of a BSGS chain without using the "short word" heuristic of Minkwitz, with the Minkwitz stuff applied as a post-processing step (the methods corresponding to Minkwitz are prepended with `words`) -- and this post-processing step is only applied when factorization is asked for.

If you want to have a dig at it, I suggest extracting the Minkwitz code in a different class (see #6 ) first. Or even starting with #9, as then the structure of BSGS chains will become familiar.

That said, I had some non working code for `FillOrbits` in a previous commit
```matlab
         function fillOrbits(chain, l)
             it = chain;
             while ~it.isTerm
                 orbit = {};
                 for i = 1:it.orbitSize
                     if ~isequal(it.uInvW{i}, [])
                         orbit{end+1} = it.orbit{i};
                     end
                 end
                 it1 = it.next;
                 while ~it1.isTerm
                     xs = {};
                     for i = 1:it1.orbitSize
                         xw = it1.uInvW{i};
                         x = it1.uInv{i};
                         if ~isequal(xw, [])
                             for j = 1:length(orbit)
                                 o = orbit{j};
                                 p = chain.A.leftAction(x, o);
                                 c = false;
                                 for k = 1:length(orbit)
                                     if chain.P.eqv(p, orbit{k})
                                         c = true;
                                         break
                                     end
                                 end
                                 if ~c
                                     xInv = chain.G.inverse(x);
                                     p1 = chain.A.leftAction(xInv, p);
                                     ind = it.orbitIndex(p1);
                                     tw = it.uInvW{ind} * xw;
                                     if tw.length < l
                                         if isequal(it.uInv{ind}, [])
                                             it.emptyWords = it.emptyWords - 1;
                                         end
                                         it.uInvW{ind} = inv(tw);
                                     end
                                 end
                             end
                         end
                     end
                     it1 = it1.next;
                 end
                 it = it.next;
             end
         end
```

**Comment by denisrosset** [comment]
We do not implement word factorization anymore. This may be helpful in the future to control numerical precision (?).
