### ISSUE TITLE
Making sure all classes/functions in the root folder are documented in the API

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#554]
# Documented classes and functions

### Classes

- [x] replab_Version – Describes and manipulates RepLAB version identifiers

### Functions

* [x] replab_checkhelp – Checks the soundness of documentation comments

- [x] replab_generate – Code generation function

- [x] replab_release – Releases the current develop branch contents as a stable release

- [x] replab_runtests – Tests the library functionalities.

### Classes

* [x] replab.AbstractGroup – Finite group defined using a presentation: a set of generators and a set of relations among generators

* [x] replab.Action – A group action describing the action of a group on a set

* [x] replab.Atlas – An atlas of finite groups

- [x] replab.AtlasEntry – Describes an Atlas entry available in the replab/atlas directory

- [x] replab.AutomorphismGroup – Describes the automorphism group of a group

- [x] replab.Character – Describes a character

* [x] replab.CharacterTable – Describes the real or complex character table of a finite group

- [x] replab.ClassicalCompactGroup – Describes a classical compact group of square real/complex/quaternionic matrices

* [x] replab.CommutantVar – Sdpvar matrices subject to symmetry constraints.

* [x] replab.CompactGroup – A group equipped with a Haar measure

- [x] replab.ComplexCharacterTable – Describes the standard character table of a group

* [x] replab.ConjugacyClass – Describes a conjugacy class of a finite group

- [x] replab.ConjugacyClasses – Stores information about the conjugacy classes of a group

* [x] replab.Coset –

* [x] replab.CosetTable – Describes a coset table

* [x] replab.Cosets –

* [x] replab.DirectProductGroup – Describes an external direct product of compact groups

- [x] replab.DirectedGraph – Describes an immutable directed graphs

- [x] replab.DivisionAlgebra – Describes an encoding of a division algebra using real or complex matrices

* [x] replab.Domain – Describes a set of elements with a common structure

* [x] replab.DoubleCoset – Describes a double coset in a group

* [x] replab.DoubleCosets – Describes the set of double cosets in a group

* [x] replab.Equivariant – Describes a vector space of group-equivariant matrices

* [x] replab.FiniteGroup – Describes a group with a finite number of elements

* [x] replab.FiniteIsomorphism – Describes an isomorphism between finite groups

* [x] replab.FiniteMorphism – Describes a morphism between finite groups

* [x] replab.FiniteSet – Describes a finite set of elements

- [x] replab.GeneralLinearGroup – Describes the group of square invertible real or complex matrices

- [x] replab.GeneralLinearGroupWithInverses – Describes the group of n x n invertible real or complex matrices, elements store inverses

* [x] replab.Group – Describes a group

- [x] replab.H – Quaternion matrix type

- [x] replab.IdentifyPointGroup – Gives information about a molecule

* [x] replab.IndexedFamily – Describes an indexed family of elements

* [x] replab.Irreducible – Describes the irreducible decomposition of a representation

- [x] replab.IrreducibleEquivariant – Equivariant space between two harmonized irreducible decompositions

* [x] replab.Isomorphism – Describes an isomorphism between groups

* [x] replab.Isotypic – Describes an isotypic component in the decomposition of a representation

- [x] replab.IsotypicEquivariant – Equivariant space between two harmonized isotypic components containing equivalent representations

* [x] replab.Laws – Describes the laws that an algebraic structure should obey

* [x] replab.LeftCoset – Describes a left coset of a finite group

* [x] replab.LeftCosets – Describes the set of left cosets of a finite group

- [x] replab.Molecule – Gives information about a molecule

* [x] replab.Monoid – Describes a monoid

* [x] replab.Morphism – Describes a morphism between groups

* [x] replab.NiceFiniteGroup – A nice finite group is a finite group equipped with an injective homomorphism into a permutation group

- [ ] replab.NiceFiniteSubgroup – A generic implementation of a subgroup of a nice finite group

* [x] replab.NormalCoset – Describes a coset in the normal subgroup of a finite group

* [x] replab.NormalCosets – Describes the set of normal cosets of a finite group

- [x] replab.Obj – Base class that provides sane pretty printing and instance equality tests

* [x] replab.Partition – Represents an unordered partition of the set {1..n} into disjoint subsets

* [x] replab.Permutation – This class regroups functions that are useful when dealing with permutations.

* [x] replab.PermutationGroup – A base class for all permutation groups

- [x] replab.RealCharacterTable – Describes the real character table of a group

* [x] replab.Rep – Describes a finite dimensional representation of a compact group

* [x] replab.RepByImages – A finite dimensional representation of a finite group

* [x] replab.RightCoset – Describes a right coset of a finite group

* [x] replab.RightCosets – Describes the set of right cosets of a nice finite group

* [x] replab.SedumiData – A block-diagonalizing preprocessor for SDPs in SeDuMi format.

* [x] replab.SemidirectProductGroup – Describes an external semidirect product of compact groups

- [x] replab.SetProduct – Describes a multiset of elements obtained by reduction of the elements of a cartesian product

* [x] replab.SignedPermutation – This class regroups functions that are useful when dealing with signed permutations.

* [x] replab.SignedPermutationGroup – A base class for all signed permutation groups

* [x] replab.SignedSymmetricGroup – Describes the signed permutation group over {-n…-1, 1…n} where n = domainSize

* [x] replab.Str – Base class that provides sane pretty printing for all RepLAB objects

- [x] replab.SubEquivariant – Describes a subspace of an equivariant space induced by subspaces of source/target representations

* [x] replab.SubRep – Describes a subrepresentation of a finite dimensional representation

* [x] replab.SymmetricGroup – Describes permutations over n = “domainSize” elements, i.e. the symmetric group Sn

- [x] replab.TorusGroup – Describes a compact, connected, abelian Lie group

- [x] replab.UndirectedGraph – Describes an immutable undirected graph

* [x] replab.WreathProductGroup – Wreath product group

- [x] replab.cyclotomic – Multidimensional array with elements in the cyclotomic field

- [x] replab.equiop – Describes a linear or affine map between equivariant spaces

- [x] replab.equivar – Describes an equivariant YALMIP matrix variable

### Functions

* [x] replab.AlternatingGroup – Constructs the alternating group

* [x] replab.CyclicGroup – Describes cyclic permutations over n = “domainSize” elements

* [x] replab.DihedralGroup – Constructs the dihedral group of order 2*n

* [x] replab.KleinFourGroup – Constructs the Klein Four-Group

* [x] replab.O – Returns the group of d x d orthonormal matrices

* [x] replab.QuaternionGroup – Returns the quaternion group as a signed permutation group

* [x] replab.S – Returns the symmetric group acting on a certain domain size

* [x] replab.SO – Returns the group of d x d orthonormal matrices with determinant one

* [x] replab.SU – Returns the group of d x d unitary complex matrices with determinant one

* [x] replab.Sp – Returns the compact symplectic group whose elements are unitary quaternion matrices

* [x] replab.T – Returns the standard torus group of given rank

* [x] replab.U – Returns the group of d x d unitary complex matrices

* [x] replab.headerStr – Returns a tiny one-line description of the object type without inspecting its contents

* [x] replab.longStr – Returns a multiline description of the given object, that fits within the given width/height limit

- [x] replab.msg – Displays a diagnostic message on the console output

* [x] replab.shortStr – Returns a one-line description of the given object, that fits within the given width maxColumns

**Comment by denisrosset** [comment]
We just need to make a release and verify that the generated site is up to date with respect to the `replab_runtests` etc functions
