### ISSUE TITLE
Splitting replab into modules

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#61]
Right now, RepLAB includes a few niceties that are not necessary for the core features to function, like the various product group constructions and the YALMIP support.

At some point, those parts should be cleanly distinguished from the core according to the following rule: extra modules depend on the core module, but not vice versa.

This means that some higher order functions in the core, such as representation decomposition, should be written in a manner that allows extensibility.

**Comment by denisrosset** [comment]
Hooks have been added with a dispatch mechanism for key functions. The group constructions are key to construct fun groups/representations for the test suite, so they won't probably be split off core. YALMIP support does not seem to require a lot of files, so it seems OK to keep this in the core `src/+replab/` folder.

@jdbancal What do you think? I'm inclined to close this issue.

**Comment by jdbancal** [comment]
It is fine for me if `CommutantVar` currently lies in the `src/+replab/` folder. A possible alternative would be to call the class `Var` and put it in a folder `src/+replab/commutant`. But I'm not sure if this makes more sense. If you are happy with the current situation, or don't see a strong reason to change, feel free to close the issue.

**Comment by denisrosset** [comment]
Happy with the current situation. `Var` is a clear Yalmip-ism. Otherwise, we could put it in a `+replab/+yalmip/Var.m` file.
The subpackage should collect all the things with the same dependency (so we can have other packages for CVX etc)

**Comment by denisrosset** [comment]
Closing for now.
