### ISSUE TITLE
is this only for scalar objects?

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#69]
From
https://github.com/replab/replab/blob/f492d74c18394e2583d9d80a62a9fbfbb04016c3/%2Breplab/%2Bstr/longStr.m#L16
it seems that the nice printing with details is only provided for two kinds of types:
 - scalar objects
 - scalar structures

A priori, I would expect all our objects to be supported here, independently of whether they are scalar or not. @denisrosset : did you have an example of non-scalar object in mind which should purposefully not fall into this section?

**Comment by denisrosset** [comment]
@jdbancal I have no experience working with non-scalar structures for example, or non-scalar objects.

For lists of objects/structures, I tend to use a cell array of 1x1 scalar objects/structures. Principally because I don't want to learn Matlab idiosyncrasies and having an "array" of "things" is closer to what happens in other languages.

Are there advantages of using non-scalar structures/objects? Have you seen them in the wild?

**Comment by jdbancal** [comment]
Yes I've seen things like non-scalar objects ;-)

An object is scalar iff it contains just one element, i.e. if its size is `[1 1]` (see also `help isscalar`). Generic custom-type data objects are typically scalars, because they don't live or act on any specific vector space. A `CommutantVar` object, however, to take a random example ;-), is exactly a non-scalar object:
 - it is an object because it is a realization of a custom class (it is not a matlab fundamental type such as `char`, `double`, etc).
 - it is not a scalar because it is a matrix: it acts in a vector space even if it is not made of `doubles` (hence its size is `[d d]`, where `d` is the dimension of the corresponding vector space)

Cell arrays are indeed the appropriate representation for lists of objects with no vector space meaning :-) (sometimes people tend to use arrays to put `stuff` together as you say, mostly by ignorance I'ld assume, but I agree that this is not appropriate, and at the very best a more or less dirty (and more or less useful) performance hack)

Structures are a bit different: if a structure contains a field `name` and another one `phone number`, then an array of this structure would be like a telephone book... So in this case the dimension is an external component of the structure, therefore whether the structure is a vector or not is the predominant feature, so the code looks good!

Ok, then I'll modify this to make sure that objects are expanded by the `longStr` procedure!
