### ISSUE TITLE
Specialize the BSGS algorithms for permutations acting on integers

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#9]
Currently, the BSGS code works in a generic fashion so that base points can be arbitrary, and group elements can be arbitrary as well.

However, in RepLAB, we only need to construct BSGS chains on permutation groups.

Thus, a small project is to specialize the current implementation by:

- removing the need for a `Group` and `FaithfulAction`, thus assuming that the group contains permutations and that elements acted on are integers `1..n`,
- changing the `orbit` structure from a cell array to an integer array,
- sorting the orbit points so that they can be searched by binary search.

**Comment by bogdan98** [comment]
I have created a separate class that satisfies the three requirements above (not using Group and Action classes, uses integer arrays and binary search on sorted list of integers to build the orbits for every integer). Should I continue using the same implementation to construct BSGS chains and consequently implement the Minkwitz algorithm the way it is described in paper?

**Comment by bogdan98** [comment]
I could possibly modify the insertion of a new point in the 'orbit' function by making it a binary insertion, which should reduce the computational time, but the rest is like that

**Comment by denisrosset** [comment]
I think your class is not going to depend so much (at first) on the rest of RepLAB... why not create a small GitHub project just with it so we can directly discuss the code?

First, let's get your implementation working for the construction of groups: given a set of generators, compute the group order, enumerate elements, test whether some element is contained in the group. Would that work for you?

I need to write a few tests for that part though -- for example the construction of a few known groups such as the Mathieu groups, or the Rubik cube group, and test of the resulting order.

**Comment by denisrosset** [comment]
@bogdan98 i've changed quite a bit the BSGS code. Sorry for me working on RepLAB in bursts, as I've been travelling this summer.

You should find a cool and readable implementation of what you started in `src/+replab/+bsgs/Chain.m`. Do not hesitate to ask questions!
