### ISSUE TITLE
Testing properties of the decomposition of a complex reflection group

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#97]
See #89, as part of the resolution we introduced the test https://github.com/replab/replab/blob/master/tests/ComplexReflectionGroupTest.m

@sebastiendesignolle I'd like to know if there are properties of the decomposition that we can find in the literature and integrate as part of the result (have no idea whether the current result is actually correct).

```
 component(1): Isotypic component R(1)      
 component(2): Isotypic component R(4)      
 component(3): Isotypic component R(5)      
 component(4): Isotypic component C(8)      
 component(5): Isotypic component I(2)xR(10)
 component(6): Isotypic component R(15)     
 component(7): Isotypic component R(15)     
 component(8): Isotypic component R(20)     
 component(9): Isotypic component C(32)     
component(10): Isotypic component C(40)     
```

**Comment by sebastiendesignolle** [comment]
When decomposing the group with GAP, I get 37 irreducible representations with dimensions [ 1, 1, 4, 4, 4, 4, 4, 4, 5, 5, 6, 6, 6, 6, 6, 10, 10, 10, 10, 15, 15, 15, 15, 16, 16, 16, 16, 20, 20, 20, 20, 20, 20, 24, 24, 24, 30 ]. I can provide you with the explicit answer from GAP if you want.

**Comment by jdbancal** [comment]
If that helps, below is the matrix obtained after block-diagonalizing a 160x160 random matrix symmetrized under the group elements.

![image](https://user-images.githubusercontent.com/5440791/65340267-2874cd00-dbce-11e9-9377-6785f230bf6a.png)

Obtained with
```
dec = rho.decomposition;
Utot = dec.component(1).copy(1).U;
Utot = [Utot; dec.component(2).copy(1).U];
Utot = [Utot; dec.component(3).copy(1).U];
Utot = [Utot; dec.component(4).copy(1).U];
Utot = [Utot; dec.component(5).copy(1).U];
Utot = [Utot; dec.component(5).copy(2).U];
Utot = [Utot; dec.component(6).copy(1).U];
Utot = [Utot; dec.component(7).copy(1).U];
Utot = [Utot; dec.component(8).copy(1).U];
Utot = [Utot; dec.component(9).copy(1).U];
Utot = [Utot; dec.component(10).copy(1).U];
allPerms = G.elements.toCell;
R = rand(160);
R2 = R(allPerms{1}, allPerms{1});
for i=2:double(G.order);
    R2 = R2 + R(allPerms{i}, allPerms{i});
end
R2 = R2/double(G.order);
R3 = Utot*R2*Utot';
spy(abs(R3) > 1e-13)
```

**Comment by denisrosset** [comment]
@sebastiendesignolle

- Is the group you wrote a solvable group? Then I can check the answer of decomposing the natural permutation representation.

- I guess the answer you provided (list of dimensions) corresponds to the list of *all* irreducible representations, not only the ones that appear in the decomposition of the permutation representation of dimension 160, correct?

**Comment by denisrosset** [comment]
Oh I see, that's probably the decomposition over C. Thanks for the data!

On September 20, 2019 10:58:47 AM EDT, sebastiendesignolle <notifications@github.com> wrote:
>When decomposing the group with GAP, I get 37 irreducible
>representations with dimensions [ 1, 1, 4, 4, 4, 4, 4, 4, 5, 5, 6, 6,
>6, 6, 6, 10, 10, 10, 10, 15, 15, 15, 15, 16, 16, 16, 16, 20, 20, 20,
>20, 20, 20, 24, 24, 24, 30 ]. I can provide you with the explicit
>answer from GAP if you want.

-- 
Sent from my mobile.

**Comment by jdbancal** [comment]
Is it expected for decompositions over C that the sum of all irreps dimensions is larger than the initial space dimension?

**Comment by denisrosset** [comment]
Nope, sum should be the initial space dimension. Which does not match here!

**Comment by jdbancal** [comment]
Probably, we are comparing the decoposition of two different representations:
 - The defining representation in the case of RepLAB
 - The regular representation (which contains _all_ irreducibles representations) in the case of GaP
